<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration{
 public function up():void{
  Schema::create('users',function(Blueprint $t){$t->id();$t->string('name',191);$t->string('email',191)->unique();$t->string('password');$t->string('role',50)->default('citoyen');$t->string('statut',50)->default('actif');$t->unsignedBigInteger('ministere_id')->nullable();$t->unsignedBigInteger('service_id')->nullable();$t->timestamps();});
  Schema::create('sessions',function(Blueprint $t){$t->string('id')->primary();$t->foreignId('user_id')->nullable()->index();$t->string('ip_address',45)->nullable();$t->text('user_agent')->nullable();$t->longText('payload');$t->integer('last_activity')->index();});
  Schema::create('ministeres',function(Blueprint $t){$t->id();$t->string('nom',191);$t->string('sigle',50)->nullable();$t->text('description')->nullable();$t->timestamps();});
  Schema::create('citoyens',function(Blueprint $t){$t->id();$t->unsignedBigInteger('user_id')->nullable();$t->string('nni',80)->unique();$t->string('nom',120);$t->string('prenom',120);$t->string('telephone',60)->nullable();$t->string('email',191)->nullable();$t->date('date_naissance')->nullable();$t->string('lieu_naissance',120)->nullable();$t->string('nationalite',120)->default('Centrafricaine');$t->string('adresse',191)->nullable();$t->timestamps();});
  Schema::create('agent_publics',function(Blueprint $t){$t->id();$t->unsignedBigInteger('user_id')->nullable();$t->string('matricule',80)->unique();$t->string('nom',120);$t->string('prenom',120);$t->unsignedBigInteger('ministere_id')->nullable();$t->unsignedBigInteger('service_id')->nullable();$t->string('grade',120)->nullable();$t->string('fonction',120)->nullable();$t->string('statut',50)->default('actif');$t->timestamps();});
  Schema::create('themes',function(Blueprint $t){$t->id();$t->string('code',80)->unique();$t->string('nom',191);$t->string('icone',80)->nullable();$t->text('description')->nullable();$t->timestamps();});
  Schema::create('demarches',function(Blueprint $t){$t->id();$t->foreignId('theme_id')->constrained('themes')->cascadeOnDelete();$t->unsignedBigInteger('ministere_id')->nullable();$t->string('nom',191);$t->text('description')->nullable();$t->decimal('cout',12,2)->default(0);$t->string('delai_traitement',100)->nullable();$t->boolean('paiement_obligatoire')->default(false);$t->boolean('active')->default(true);$t->timestamps();});
  Schema::create('demandes',function(Blueprint $t){$t->id();$t->string('reference',120)->unique();$t->unsignedBigInteger('citoyen_id')->nullable();$t->unsignedBigInteger('demarche_id')->nullable();$t->unsignedBigInteger('ministere_id')->nullable();$t->unsignedBigInteger('service_id')->nullable();$t->string('objet',191);$t->string('statut',80)->default('deposee');$t->decimal('montant',12,2)->default(0);$t->timestamp('date_depot')->nullable();$t->timestamps();});
  Schema::create('paiements',function(Blueprint $t){$t->id();$t->unsignedBigInteger('demande_id')->nullable();$t->unsignedBigInteger('citoyen_id')->nullable();$t->decimal('montant',12,2)->default(0);$t->string('moyen_paiement',80);$t->string('reference_transaction',120)->unique();$t->string('statut',50)->default('en_attente');$t->timestamp('date_paiement')->nullable();$t->timestamps();});
 }
 public function down():void{foreach(['paiements','demandes','demarches','themes','agent_publics','citoyens','ministeres','sessions','users'] as $table)Schema::dropIfExists($table);}
};
